apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: saas-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/camou92/LinkedIn-System---Microservices-Platform
    targetRevision: main
    path: k8s/
    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: saas-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data